apiVersion: v1
data:
    credential.json: ENC[AES256_GCM,data:OLSzaXTnXk3mZmgvenGLSc6NbxwHo1O4ePE36K6sFd0765rqIu9vrVWB9n2DKKhxTn1KegZW5O/trECLsquzReZ7k9j33rkacOX6UPm3R1rTunIZHuohrPA1FxsuA/qGjcPlBupZ8yCuGABOVWc4TWLDqe3Dom7IO+cV90jsVVr+gRD7WsncbkBTa0odHIdB1oyfRQ01N7+QSaz3zFAGOAVemJQxeyRL8sTNZf4LRDqKEkBRdM9sLIoDd6InSEHj2NF3H4LRti3AX9IpCfD8M5urLIj2K7STyHiJCEfSg94vi6A671VyVFPMou0=,iv:VVu9vEty9orgXCirD7l1OI0a+5aoUJGAjOy8XTP94aM=,tag:FwiBLDDQz6FmD/w8ZlycnA==,type:str]
kind: Secret
metadata:
    name: audiobook-tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TmNIWGJhVnNERGM1WGtW
            RS9XdW5yUVFxSjhMMEdXWVBOVUtjV1k1SHlFCnNUYjdNUDB3UEwvZWZFYzdZZlBi
            YlZBZWY0NnhOcmZpNU56Mi90anM3ME0KLS0tIGVmemlwRmFPcnoxcnUxOHFEV0Ry
            amFidndZTkZjL0d4SStVcnJqQ3Z4T2MK8dc6YO2EV/wWVRHayyIzTc5WY0iLY/GB
            VhhebZlaWRLBH1CmZJ7egZBMBdS5HCPXKAAIlpbUIbHZTMqSxWpiJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p9mjcxyekqarlz7eef5qq6mmpvjr788camhnq64nesj3y4xhudjs3tn37j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T08:40:55Z"
    mac: ENC[AES256_GCM,data:jmgPLrn2Xwtzh92pFFQGFRKxAU9XN/IE4MJWVRp2VWYekAoTG3MpSpqVHr5u8IPThGeSbVhZqtwdiLHfm4npAJW5PnLQEcgse60Rn0y1Uwcjg9gA7Gd0zGCWZED5FW8P/9lFKt3+VKaMU5MWH5YtVZX8wN8RJd6BzUnm/DsIkY4=,iv:ScbaAWY8FakoElgoz7yueiHiKRt/bRMzoXihQO8UB18=,tag:qwLMszHj0ANWDBd0ncjEzQ==,type:str]
    version: 3.13.3
