apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:BsTKYKo4oVMHkbdHSUrUAjopn8WRQYQDM9kDD9Hp8jF5uvr2CM0RQj6ZhxuRz7QUDYaIgT8L0LDVfsYFIJzpH9XvX9RTPUgLRes5sw3v++hTyBMN,iv:KoFgxSyl5buKkWx1EzauwXVyY+6SfePMHRp9fVxKuoc=,tag:y9e1pzH1COsyp50jBbXmHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBya2FvcUpoU05TS2ZHSEJQ
            cnhzWHpSS05vYVJNOTJDR1hoNXdhenZ4YkRZClhpcGJkVEhxVGZNUkd1cm1QS3Iw
            VHFTT1MzbWZuTG5CVitUa0xwOEFWVVkKLS0tIG03emVjRnFtSGY5Zy9SOUtWY2Q3
            NnFMZ01LTnUzd3dadUVseW8valR5RDAKgZTQZXZjAs0I1og0EmGDz0cdAHNp0Cy4
            X+9THI4jFb996H3N545sZCqwnkpd70eMBgm6MienBJxoFyqsYhS8EA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p9mjcxyekqarlz7eef5qq6mmpvjr788camhnq64nesj3y4xhudjs3tn37j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T20:59:04Z"
    mac: ENC[AES256_GCM,data:E9ejmK3Hnm9nha1dQ23TWruC4aDUGRBuKQzhr42IoIVaozBpdQAqrcwP5U+CrS+ZxvzXyl1Qb6ZbirgO5siQW7hMib/8lfbDJ/RUwMtzMXKWqJjIh6MKT3mpdZyhi24XdONRsogzDoOSDTE8afVk4LrdCbzqvoF9zfNyV+LnDw8=,iv:QRXu2eJQ4N7sc8GDbnT22q29g9LCyHBY+uKPH4+PpT4=,tag:BFKrTBX0jf42eQ63umC/jA==,type:str]
    version: 3.13.3
