apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        fcGroup: 33
      containers:
      - name: linkding
        image: sissbruecker/linkding:1.44.2
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: linkding-data-claim
          mountPath: /etc/linkding/data
        securityContext:
          runAsUser: 33
          runAsGroup: 33
          allowPrivilegeEscalation: false
        envFrom:
        - secretRef:
          name: linkding-secret
      volumes:
      - name: linkding-data-claim
        persistentVolumeClaim:
          claimName: linkding-data-pvc
