apiVersion: v1
kind: Secret
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Nxo8EWctdNR47TeXh/5guQ==,iv:r4Riyo4txORF29lO5qUfvx0jUJEczo+CjG8mtr7fL4M=,tag:21/WBR6xz4y5JJbVTAphHw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:ZK02pKsYu0gao8ha,iv:TwORvJiceccKbZ8dCaXLpF4hnu68Ak4sqZ29OfD0YW8=,tag:bxlWnCabM2ok2eumXErqLw==,type:str]
metadata:
    name: linkding-env-secret
sops:
    age:
        - recipient: age1p9mjcxyekqarlz7eef5qq6mmpvjr788camhnq64nesj3y4xhudjs3tn37j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WmtlaHZYTFVlVEpLOEhl
            ZnNaM3R6U2NXYmJJMGFUS3VZSk44YXlEZFFzCjVxeHRVZlBicXE3a1Z5VDJ6QXZL
            eE5lQ1FMcnd1eWl3RVZ1eTUrTWllWlkKLS0tIGEzaUM0R0VyYzVKdGEvb0o3NU41
            RjJBQ1NhMllpK0JxRE5Fa0dpdUdGY0UKMnBWz83obWYa7wfEWryXXds7j3GShj2q
            An6bZbeSPQRHLJzwszNGk9hBHkDNcjXJlP+kBNlV3t5reyTfWiv4eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T20:03:27Z"
    mac: ENC[AES256_GCM,data:x5WKWx94olr0JWKGtn4IdORDupfzLP5cFfO3YByj+R7IhB9HvPgFjmtadH7xdTBNvVgmySUvrTuLueyxSki7+WaQnh7+Cu3sHypgDc7xyNbTOs1sE5n0HapHYepxTF6XoqGHnFK/tdUhG4x1d8NAKvXBCsfn31tTAWvchJflVPI=,iv:bx7ZDwtHeI2A4K5Ecj+ZhMAsdRXhOf9DCGzDHquoi/8=,tag:qrRJi7IGQwvnuv2WlUA26g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
