apiVersion: v1
data:
    credential.json: ENC[AES256_GCM,data:NyGtzMylmz9iNrGHvzt5SJtlOacvJsUjHOoabOSkKcoU46JMw6NllkoVPboBbn1xPHZVCET26ueI77Yvoy3aQ80Vx/ugDdH5VswMKD4bxYOSHubXip2G6VUPe5NH4GehkQhAbTN5Xbkl9kaxZnt9CagoHrM8wumPykIUpVlzSVpFXIW/MjKhpaoe/Gcrgd6EMVWk9DH9LAgraCa+RqcPBfZxUpNFZGnQ33v02H1I4yAbvFyK2KcOV09etIYisygzvhK5g+kJYWDcAhIGhZsEn2EYyXBBJVMixlb5uJdqjn0XLjsxbsEF7bY58dU=,iv:tvM69fEtR1Ja/06BCxS1rOhUXUSiBWy5eW1mN0/8Jbs=,tag:mlp8PXetGNEjIwkKIj7Cqg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1p9mjcxyekqarlz7eef5qq6mmpvjr788camhnq64nesj3y4xhudjs3tn37j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRTkwTHdHVEk0THdxc29D
            UWFkSkNLOXZLNFhQTTJmV1o5Uy9ybG5nRURzCmliajQvdy9NR015UzFidHBucWY5
            RStKNEpUdHZTc3Rzd3R5dXJYNkcwdFUKLS0tIEZFL3UweTJQbDhwTDZqQkVlY0No
            b3NZN2ZLMGNFVU5keEZYbGw1alVScEkKP5ubvx5CZtkOnAla6l+ptaediBEo+GpO
            fGfd1lV4zKZ9TWF313b4CVJbe3uXGdb/fobVpPRZK3UcYjTXkg2dTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T16:37:29Z"
    mac: ENC[AES256_GCM,data:MBLcqHRQVdD8jWw8rltFiSlnzooOTSb7PeguF7z9Do7diISfPmTy0PB+mxLyDFZh+xSqybRJ7DNaJk2b97pdIlViACsaqWrgTFuR+ePCdtMuh25p3Feiay56qc4iqpeoEbd3XeNnrPxs0OrYpNFevA+JEOQ44hqpEdkQr5fFUx4=,iv:Z/hBKljiavoLurVzwGulRLbbmhxdhjIhZXW8/vMsOG8=,tag:MBc1z8gKGldTUmq+HUBvjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
