apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale
data:
    TS_AUTHKEY: ENC[AES256_GCM,data:J5LcCIpPRyXj1aSh7jr2yPgZGlPeK6TwvLi7SkkNgohkw5a9v2eAZNOCMLE3YVEeujtyMvlnDfG2B9yS8chdd5blNoQjtKTqZFHiXeT7CVE/U7Ul,iv:w+VvlJiit3TWDcevpG1bAjAnqMgCMlqkctUJxvheRsE=,tag:ISY9Gwm8QBK5M2BTZFHg6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVd1pJY1lobk5tSW8zTW5n
            UGFaQmFWRVBFVjEyeFFLNDgwWDh1VUNMaVdvCjZQOWFRai9EWjVxMk5EdzZBZTlM
            WnY0UDV1c0tkSmp5bk1lbmdnaXpSTzAKLS0tIGE5QnJ2YS8wamppVnF5bjRhNEtx
            Yzc5Vmh3NmxpQmE5K0tvdlBoREluQ0EKSPKqMpKDf36aSEdDEG07RzIFbCSk2lFO
            ZefSio2rZK3EpQl1wGxzvSp7haDqmCv7g1gN33ka4VgDzmoK51RCFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p9mjcxyekqarlz7eef5qq6mmpvjr788camhnq64nesj3y4xhudjs3tn37j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T02:38:31Z"
    mac: ENC[AES256_GCM,data:dINlLuwdJWPNO8eB4nq+rVdcFG0FmktQwwPM8qCIBR7HBgnVZlJqzmb1aPIpcfV/AT9r7E5H8wpFYLQIj8KxKNmWSkcXcMQuMWO6Owas2w0HWTzVpUBmDZY2U+1UUs5K+YgX4DmCbQk/TfuOeV4QrrPNNSCfB+stVoUL09iIwhw=,iv:u69KVBT0WRtfsheq/Q/DHVCah9OB0HFq9YZMheJ9mUc=,tag:bqNh7SVEwgX0DDZpAKAtOQ==,type:str]
    version: 3.13.3
